### ISSUE TITLE
CSS Fixes (B01-SRV)

### ISSUE THREAD

**Issue by ItsAnkan** [destryptor/MASK-W23-Sharanya-22CS10088#5]
(since this is a backend task, you can ignore these, but I'm gonna list these anyways :))

Even if this is a backend task, your frontend is good, it looks neat and clean. Here are some improvements that you can make -

- While 33% width looks good on desktop, it looks a bit too small on devices with less view-width. To fix this, you can use [`@media` ](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) queries, or you can make width something like `max(33%, 300px)` which will limit the size of boxes.
- On clicking the date input, the box expands a bit, fix it maybe (adjust font-size, or height of the box, or find out how to fix it).
- Make textarea to not be resizable.

**Comment by destryptor** [comment]
Made the required changes in the style.css file. Thank you for reminding me about responsiveness. Made the other fixes as suggested. Thanks :)
