### ISSUE TITLE
Error Messages / Post-Submit (B01-SRV)

### ISSUE THREAD

**Issue by ItsAnkan** [destryptor/MASK-W23-Sharanya-22CS10088#8]
After submitting the form, the "Thank You" page comes up regardless if the form has been successfully entered in the database or not.

While this is not a serious problem, but it'd be better if you show proper error messages after submitting the form (either a popup or an error page)

**Comment by destryptor** [comment]
This issue should be fixed now, I implemented sending the status messages appropriately to the function in the html which sends the post requests. It checks whether the success message has been sent or not, and then only redirects to the thank you page
