### ISSUE TITLE
Code restructuring

### ISSUE THREAD

**Issue by Goose-Of-War** [destryptor/MASK-W23-Sharanya-22CS10088#9]
There's definitely some major restructuring which has been done since day 1, but there are other things you can fix too. Ping me when you are free. Will explain it over a meet or something.

**Comment by destryptor** [comment]
I completed the restructuring as you suggested, it should be almost like what you wanted. If there are further changes required, do let me know

**Comment by Goose-Of-War** [comment]
Lmao
